### ISSUE TITLE
[Question] - Any specific reason for deprecating  custom components in 6.0.0-rc1?

### ISSUE THREAD

**Issue by dinbtechit** [formio/angular#1040]
why custom component is being deprecated in Angular FormIO? Are there any other alternative options that you would recommend?

ChangeLog: 6.0.0-rc1

> Version 6.0 will official deprecate the Custom Components using Angular Elements feature. https://github.com/formio/angular/wiki/Custom-Components-with-Angular-Elements. If you wish to still use this feature, you will need to manually migrate the component code provided @ https://github.com/formio/angular/tree/5.5.x/projects/angular-formio/src/custom-component into your own application.

**Comment by travist** [comment]
While we were very appreciative of this initiative, it was developed by a developer who submitted it as a contribution, but was not able to provide complete support to the developers that adopted it. It essentially became an unsupported feature of this library, and we did not have anyone internal @ Form.io who had expertise knowledge over this work. Because of this, it provided a source of friction and we decided to deprecate it from the "official" repository.  

I personally believe that this module was fantastic and really does deserve to be in its own library. I am hopeful that someone would take the code from this library, and create their own plugin and push it out to NPM so that it can be installed along side our @formio/angular package so that it can still be used moving forward. In that case, however, it would be maintained by the person who contributes this library to OSS. We just as a company (Form.io), who are responsible for maintaining this OSS library, could not continue to support this feature.

**Comment by dinbtechit** [comment]
@travist  - Thank you for the response. That makes sense. the code seems fairly straight forward. I think our organization could be able to push this out as a separate npm package and maintain it for everyone to benefit from.

**Comment by muneebahmad0600** [comment]
@dinbtechit were you able to create a new library for custom components?

**Comment by dinbtechit** [comment]
@muneebahmad0600 - No, unfortunately, we did not get a chance to create a separate repo for this. But you might want to consider maintaining it within your source code, for flexibility reasons. I would recommend recreating an "angular lib" and putting the code there.
