### ISSUE TITLE
[Question] - How to create formio module as a Angular Library?

### ISSUE THREAD

**Issue by dinbtechit** [formio/angular#1043]
How to create formio module - https://github.com/formio/module-example as an angular library?

**Comment by travist** [comment]
You can import the core renderer in your application, through the Angular package and then add your module there.

```js
import { Formio } from '@formio/angular';
Formio.use({
  ...
  ...
});
```

It should be noted that this module from this library is old and may not work as intended since it was written for the 3.x version of our renderer, and we are currently about to roll out the 5.x version.

**Comment by dinbtechit** [comment]
@travist  - Thanks for the reply. Maybe I am not asking this question correctly.

The text discusses Formio Modules, a concept mentioned on the website (https://help.form.io/developers/modules) that allows users to customize templates, components, cssClasses, and providers. While there are examples available demonstrating the usage of Formio Modules as a separate npm package, the text mentions that the development experience can be cumbersome as developers need to constantly rebuild the package and restart the Angular app when making changes to the template. 

I want to take advantage of the angular's hot reloading to improve my development flow. So, instead of having a separate npm package or project for this, I'm wondering if there is a way to include my custom "Formio Module" as part of my angular monorepo project as an angular library.
