### ISSUE TITLE
How can I Update the ROLE of the USER?

### ISSUE THREAD

**Issue by testgkyb** [formio/angular#203]

**Comment by wag110894** [comment]
Hello,
This is William with the Form.io support team. Thanks for reaching out.

Roles can be added to users with the "Role Assignment" action on a resource form. How we typically do this is to have a resource like "User" and then add a Role Assignment action on it to add a specific role to the users in that resource. In addition, you can make this conditional based on values in a field to add different roles to different users. This action only runs when a submission is created or updated so you will need to keep that in mind for existing users.

We also have support packages available for training, support or development services if you are interested! Otherwise, we have a great user community available in Gitter for support.

Please let me know if you have any further questions or concerns.

Thanks,
William Gay
Form.io Developer Support

**Comment by bhushankumarl** [comment]
@wag110894 
Is it be possible to Update User Roles through API call?
e.g One User has been Registered to have Role Employee but later on, someday I want to promote Role of the Manager to same user.

Reference: https://documenter.getpostman.com/view/684631/formio-api/2Jvuks

**Comment by wag110894** [comment]
Hello Bhushankumar,
 
This is William with the Form.io support team. Thanks for reaching out! 
 
You can add multiple Role assignments (and unassigns) to the User resource and make them dependent on a "Role" field in the User resource. Then when you set the role field it should trigger the corresponding Role Assignment action.
 
We would love to connect hear about your project and see how we can help.   Additionally, our on premise deployment allows you to deploy our entire platform within your own infrastructure giving you complete control over your data.  
 
And finally, we also have support packages available for training, support or development services if you are interested! 
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by bhushankumarl** [comment]
@wag110894 
Thank you for a quick reply.

I want to do it programmatically, using Angular.

Can you point out me to API that updates the existing User's Role?

**Comment by travist** [comment]
We currently do not allow an API method to explicitly change the role of a submission. This would have to be done using the Role Assignment action attached to that form and configured for the "Update" method.
