### ISSUE TITLE
how to render json object in datagrid table

### ISSUE THREAD

**Issue by iamsandeepgupta** [formio/angular#227]
I have a data inside json object i just want to render the data in the datagrid with gridtype=form.
i have passed my json object in query attribute but not able to successfully load the data inside the grid.
I am using Angular 5. Please tell me the solution as i have been stucked on this since last 5 days.
@travist

**Comment by jhen1422** [comment]
Hello Sandeep,

This does require one of our developers to work with you or provide documentation. Please let us know if you are interested in our support package pricing. Thank you!

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
