### ISSUE TITLE
Custom validation not working for components placed inside datagrid.

### ISSUE THREAD

**Issue by rubandangol** [formio/angular#247]
It works in the portal, but not in the application. We're using angular-formio 3.10.2 and formiojs 3.13.6.

**Comment by travist** [comment]
Thanks. This sounds like a bug. We will add this to our planning discussions.

**Comment by imshivamchauhan** [comment]
any update on this?

**Comment by abhishek0196** [comment]
Data validation doesn't seems to works for a custom component.

**Comment by wag110894** [comment]
I am not seeing any issue while using angular-formio 5.0.0 and formio.js 4.12.4. Can you provide a JSfiddle of the issue?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
