### ISSUE TITLE
Accessibility support for component's lables

### ISSUE THREAD

**Issue by moshefi** [formio/angular#273]
Hi,

The "Formio" client app form-builder generates textbox labels correctly with a "for" attribute that points to the input element.

The "angular-formio" doen't generate a "for" attribute inside the label or a "aria-labelled-by" attribute inside the input element.

This simple relation is required for accessibility and correct output for screen readers.

Can this be added ?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
