### ISSUE TITLE
multiple column drag into fieldset

### ISSUE THREAD

**Issue by bhupendrapatel-zz** [formio/angular#279]
I am using form.io with my angular 7.2.0.
Everything is working fine but i am facing one minor issue regarding adding multiple column into fieldset layout.
First add fieldset layout in from.
Then Add column inside fieldset.
When we add second column in that fieldset without changing label, it is replacing first column.

Same issue not produced on form.io angular demo.

Please check issue at following git repo:
https://github.com/bhupendrapatel/formio-demo

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
