### ISSUE TITLE
core.js:15723 ERROR Error: Uncaught (in promise)

### ISSUE THREAD

**Issue by irsmart** [formio/angular#282]
Using Angular, when I try to submit a form with validation errors I get the above error. Submit works fine on a valid form.

Does anyone know how to avoid or fix this?

Strangely though, a wizard form works fine on submit despite complaining that the FormioWizard class needs to be instantiated.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
