### ISSUE TITLE
submit button is messed up on click

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular#283]
Run example https://formio.github.io/angular-demo/#/forms/builder and click submit
see issue with button on submit
![92c2b5ba917f37b7df995ad2d26ed19d](https://user-images.githubusercontent.com/3460517/55522129-87eb1a80-5638-11e9-9f1e-4dfc4f2f9f91.png)
![9715f608a360c8c2d23866966819ab38](https://user-images.githubusercontent.com/3460517/55522130-87eb1a80-5638-11e9-8cee-dc9b7ecba39c.png)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
