### ISSUE TITLE
Resource in Select Component not binding dropdown

### ISSUE THREAD

**Issue by imshivamchauhan** [formio/angular#285]
In Select Component, in Data Tab select Data as Resource and then select already created resource form, the select key in Html Template that exists in resource from.
 
Issue: Drop-down doesn't get bind using the resource.
Some imp info: api is getting hit for fetching submission in F12 Network menu, in submission api, data is perfectly received at browser, but drop-down doesn't get bind. May be some issue is with your HTML template {{item.data.someKey}}

Attachment of configuration:-
![image](https://user-images.githubusercontent.com/33184564/56019582-a9c45b80-5d22-11e9-904b-5c10ef6064d0.png)

![image](https://user-images.githubusercontent.com/33184564/56020029-c1e8aa80-5d23-11e9-99ef-6724044f1be1.png)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
