### ISSUE TITLE
Custom css not effective

### ISSUE THREAD

**Issue by KP-story** [formio/angular#314]
i want to change height of form. it default is min-height =80px and i
write in my component css like .formio-form {
    min-height: 10px
} but its not effective. can you help me.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
