### ISSUE TITLE
[BUG] User icon appearing in day component fields in safari

### ISSUE THREAD

**Issue by rubandangol** [formio/angular#315]
When focusing on empty day component fields, a use icon appears. This is only happening in safari.

![image](https://user-images.githubusercontent.com/15991812/60017909-a0078e80-96a9-11e9-918e-d7ad6a657960.png)

**Comment by travist** [comment]
This may be caused by the wrong versions or conflicting versions of font-awesome are being loaded. Please verify that you are only loading a single font-awesome library.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
