### ISSUE TITLE
[BUG] Search input not cleared when exiting combo 

### ISSUE THREAD

**Issue by LorenzoReply** [formio/angular#354]
When i enter search query in combo, the search field is not cleared if i exit combo without selecting a value.

**Comment by jhen1422** [comment]
@LorenzoReply Thank you for the report. We have added this item to our platform backlog. If you are interested in expediting the resolution, please contact support@form.io for pricing information.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
