### ISSUE TITLE
Documentation of Data Table or Grid

### ISSUE THREAD

**Issue by dmenne** [formio/angular#371]
Sorry, there are no pull requests for the [Wiki](https://github.com/formio/angular-formio/wiki/Data-Table)

Is:
`import { FormioGridModule } from 'angular-formio/grid';`
Should be:
`import { FormioGrid} from 'angular-formio/grid';`

Naming is highly inconsistent: Sometime "Data-Table", "Data Grid", "Data Table", formio grid.

Suggestion: Only use `formio-grid` or  __Formio Grid__:  In any case, get rid of the "Table"

**Comment by dmenne** [comment]
Also in angular-demo `data-component.html`
<p>The data table is provided through the <code>FormioGridModule</code>, and provides you a way to easily embed a data table within your application with the following code.</p>

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
