### ISSUE TITLE
Documentation of Form Manager

### ISSUE THREAD

**Issue by dmenne** [formio/angular#372]
Documentation of [FormManagerIndexComponent](https://github.com/formio/angular-formio/wiki/Form-Manager)

`export class IndexComponent extends FormManagerIndexComponent {}`

is misleading. This constructor requires 4 or 5 (with auth) parameters and a super.
```
 constructor(
    public auth: FormioAuthService,
    public service: FormManagerService,
    public route: ActivatedRoute,
    public router: Router,
    public config: FormManagerConfig
  ) {
    super(service, route, router, config)
  }

```

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
