### ISSUE TITLE
Consider splitting up FormioModule

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular#377]
Formio has a builder and a viewer. Right now its bundle together in one module on angular, thus very heavy. Consider splitting into 2 modules one for viewing and  one for building.

**Comment by aiwebb** [comment]
Agreed - one of our priorities for v5 (2020) is to move toward a more modular architecture that will allow us to ship much smaller file sizes. Things like this are definitely on the list as candidates for splitting up.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
