### ISSUE TITLE
Error: Template parse errors: Can't bind to 'columns' since it isn't a known property of 'formio-grid'.

### ISSUE THREAD

**Issue by anortega** [formio/angular#396]
How to display selected columns only in formio-grid?

I keep having an error whenever I specify a columns to be displayed.

Like this:

<formio-grid src="https://stage-rizsnddzzqmvwik.form.io/timesheet" [columns] ="[{field: 'data.date', key: 'date', label: 'Date' }, { field: 'data.totalTime', key: 'totalTime', label: 'Time' }]"></formio-grid>

This is the error:

Error: Template parse errors:
Can't bind to 'columns' since it isn't a known property of 'formio-grid'.
1. If 'formio-grid' is an Angular component and it has 'columns' input, then verify that it is part of this module.
2. If 'formio-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("align-items-center">
            <formio-grid src="https://stage-rizsnddzzqmvwik.form.io/timesheet" [ERROR ->][columns] ="[{field: 'data.date', key: 'date', label: 'Date' }, { field: 'data.totalTime', key: 'tota"): ng:///AppModule/TimesheetComponent.html@22:79 compiler.js:2175
    Angular 5
    forEach self-hosted:3491
    Angular 8
    ts main.ts:11
    Webpack 8

Am new to Angular, please let me know what's wrong here.

Thanks.

**Comment by bh-adrienne** [comment]
@anortega , I'm answering here because I had this exact issue and it took me way too long to figure out.  TL;DR: for those reading: this can be done, but it is NOT supported by the library at this time. 
(If someone has the time to get the code I uploaded here into the main code base it would be nice...)


Steps: 
1. You should read up on Angular @Inputs, since what you are trying to specify with 'columns' is an input. Here's a [tutorial of how @Input values work](https://ultimatecourses.com/blog/passing-data-angular-2-components-input). They aren't just any old properties like in HTML. They are special. 

2. Once you read up on that,  this is the documentation for @Inputs available on the formio-grid component: 

https://github.com/formio/angular-formio/wiki/Data-Table

The input you want to use is actually called "query".  The "query" is a **JSON object** that then gets flattened into a form.io remote call for what you want.  For mine, an example JSON object  looks like this: 

```
{ limit: 10, 
select: 'data.billing_company_name,data.billing_company_email,data.billing_company_phone', 
skip: 0 }

```
Note: I had to reverse engineer this format from the Query string that the form.io Postman backend API documentation uses here, specifically the section entitled ['Get all submissions within a form': ](https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest#1f207caa-9d04-3e81-2973-e4bf82ee5190)  It would **also** be super great if someone had the time to document in the angular-formio wiki section for the 'query' what the query had to look like to actually work and what the angular component did and did not support because, surprise, the postman API options are only **partially** supported in the angular-formio library. 

3. At this point, you would think that this would be enough once you have an Angular component with the following property: 

```
this.myQuery = { limit: 10, 
select: 'data.billing_company_name,data.billing_company_email,data.billing_company_phone', 
skip: 0 }; 
```

And your component html will look something like this: 

`<formio-grid src="https://stage-rizsnddzzqmvwik.form.io/timesheet"  [query]="myQuery">
`
... BUT THIS ISN'T SUFFICIENT. Your table body will be right, but your column headers will be wrong because the header inside 'formio-grid' doesn't take into account the "query" input at this time.  So... there's 1 more step I had to do. 

4. Import the following component into your Angular project. It's an extension of SubmissionGridHeaderComponent from the angular-formio codebase, except it takes the 'select' value from the query input into account. 
[selectedcolumnsheader.component.ts.zip](https://github.com/formio/angular-formio/files/4013496/selectedcolumnsheader.component.ts.zip)

5. The <formio-grid> component also takes a [tableComponents] input so you can custom define tables. Use this to override the <formio-grid> table components: 
```
this.myTableComponents = {
    header: SelectedcolumnsheaderComponent,
    body: SubmissionGridBodyComponent, //this is the default angular-formio component
    footer: SubmissionGridFooterComponent //this is the default angular-formio component
  };
```

And then the component html: 
```
<formio-grid src="https://stage-rizsnddzzqmvwik.form.io/timesheet"  [query]="myQuery"   [components]="myTableComponents">
```

6. FINAL NOTE: The TABLE VIEW IN THE FORM.IO BACKEND IS A LIMITER ON WHICH VALUES YOU GET BACK. Basically, if you have a Form.io form where your table view box is not checked on a widget, that value is NOT coming back, even if you ask for it in query form. What I had to do to make all the above work was basically default to making ALL widgets viewable in the Form.io backend tableview, and then use my angular-formio code to filter them out. So if for some weird reason you can't change your backend to show all the columns by default, then the above solution is completely useless to you.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
