### ISSUE TITLE
Select Component

### ISSUE THREAD

**Issue by kausttubhs** [formio/angular#423]
Hi team I want to have my own Data Source Type options in Data tab for select component. I have been trying to do it using edit form object. It's not working could someone please help me with the code for this.

**Comment by aiwebb** [comment]
@kausttubhs, can you supply either a JSFiddle or some example code for us to take a look at?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
