### ISSUE TITLE
Remove buttons don't work

### ISSUE THREAD

**Issue by ghost** [formio/angular#433]
Scenario:
Both Angular 7 and Angular 8
angular-formio 4.4.2

In `<form-builder>` every "remove" button on top of each component doesn't work. Console doesn't log anything and nothing happen.

**Comment by travist** [comment]
Works for me https://formio.github.io/angular-demo/#/forms/builder. ...  what browser are you using?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
