### ISSUE TITLE
Output Custom Event on Button Click

### ISSUE THREAD

**Issue by chandranalini** [formio/angular#445]
Hi, 
Please share the example to fire output custom event on button click using angular 8.

**Comment by merobal** [comment]
https://github.com/formio/angular-formio/pull/443

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
