### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by fzucaro** [formio/angular#449]
# FORM DATA INITIALIZE
I can initialize data form by 'submission' input. Usually i set a json in the format {field: value}. The question is if is possible and how can design the form in order to group fields logically, so data could be: { user: {name: 'ssss', email: 'a@aa.com'},address: {street: 'sss', zip: '11'} }.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
