### ISSUE TITLE
EditForm open automatically 

### ISSUE THREAD

**Issue by sarashid** [formio/angular#451]
EditForm open automatically when i drag and drop  component, is there any way to stop this behavior and just let it open when i click edit icon only?

**Comment by travist** [comment]
This would need to be a feature request in formio/formio.js.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
