### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by prabas88** [formio/angular#453]
I'm trying to remove the unwanted components from FormBuilder in Angular 8. I tried passing the options similar to JavaScript version of formIO but it doesn't give any change in the UI.

**Comment by GabrielDambroski** [comment]
I put it like this

`<form-builder [form]="infotipo"></form-builder> `

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
