### ISSUE TITLE
File upload component

### ISSUE THREAD

**Issue by krixerx** [formio/angular#46]
Would like to have file upload component like ng-formio has.

**Comment by travist** [comment]
Hello @krixerx,

I will be working in this library this week and will do what I can to introduce the file upload component. 

Thanks,

Travis.

**Comment by amccubbin** [comment]
Any updates on this component? Need this functionality ASAP for angular project with formio. 

I would be willing to contribute time to help integrate a third-party file upload library if necessary, but would be good to know current status of development on this component.

**Comment by krixerx** [comment]
Same question, any updates on this component? Just tried latest ng2-formio (1.0.0-beta.4), it says "file" is "custom" component type.

**Comment by rmckeel** [comment]
I am also interested in this.  For now, I will need to move a project to ngFormio unless there is a file upload component soon with ng2-formio.  I have worked with FineUploader, so that is a possibility for uploading, but I don't see / know how to do a custom component for ng2-formio, so I don't think I can integrate myself.
