### ISSUE TITLE
Insert Image in  Content Component is giving an error

### ISSUE THREAD

**Issue by modi-parth** [formio/angular#463]
Hello There,
I am using the **Content Component** from **Layout tab**.
I have added some text and Want to insert images.
But when I click on **Insert Image Icon** mentioned as below image.

![ContentComponent](https://user-images.githubusercontent.com/37060879/73748673-f2507800-477f-11ea-91a3-124c415eb80c.png)

It gives me a below-mentioned error 
![error](https://user-images.githubusercontent.com/37060879/73749059-9cc89b00-4780-11ea-8f28-b55dfa06de43.png)
But when I insert the image on their official site it works.
Any help will be appreciated :)

**Comment by jhen1422** [comment]
@modi-parth Thank you for the report. We have have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by PercyBlakeney** [comment]
I have the same error. It was running ok, but suddenly it stops working and fires me the same error:

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
