### ISSUE TITLE
[HELP WANTED]

### ISSUE THREAD

**Issue by HenriqueVilela** [formio/angular#466]
Please provide as many details as you can:

 

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.4.5
- Frontend framework: angular 9.0.0
- Browser: opera
- Browser version: newest

 

## Steps to Reproduce
1. Use form renderer and try to refresh the form with the refresh event, i an not sure why this trigger the problem

 

## This happens 

 
![image](https://user-images.githubusercontent.com/38706785/73977858-e395cc80-4909-11ea-8492-847caa52acf3.png)

**Comment by travist** [comment]
We have not yet upgraded Angular to 9.x so maybe that has something to do with it. Upgrading to latest version of Angular is on our priority list so it should come soon.

**Comment by Deloriom** [comment]
@travist  also this happens when i try to use language and other inputs, some inputs like form and submission works fine.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
