### ISSUE TITLE
[Custom Components] How can I use Custom Components in PDF builder?

### ISSUE THREAD

**Issue by romapelypets** [formio/angular#473]
I have created Custom Component and have applied it to my PDF builder. But I got an error `Unknown component: customcomponent`. 
How can I use it?

**Comment by merobal** [comment]
Did you setup according to the wiki https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements and does it work for you inside the regular formio component or formbuilder?

**Comment by romapelypets** [comment]
Yeah, sure. I set up according to the wiki and it's working for regular builder, but not for PDF

**Comment by romapelypets** [comment]
Any updates?

**Comment by travist** [comment]
The PDF builder is pretty opinionated which components it allows to be included in PDF's since many components are not compatible with the PDF rendered form. As of right now, we don't have a way to indicate that you wish to include your custom component in the PDF builder, but there may be a way to hook into the options to override default behavior, but this is not something I have done myself.

**Comment by ivoscode** [comment]
Am I correct in understanding if I wish to include a custom component in to a PDF I have to alter PDF builder and not the renderer? I can get my component to work in a  PDF builder but the component is not recognised on PDF rendered form while  filling it out. Same component works fine in a "form" render.
 Any code sample on how to add custom component to pdf would be appreciated for @formio/reac
![Screenshot 2021-11-03 at 12 06 14](https://user-images.githubusercontent.com/36007368/140058618-ddb5e3ba-f5d0-4ed4-a5db-a7ba85c4508c.png)
.



.


![Screenshot 2021-11-03 at 12 17 31](https://user-images.githubusercontent.com/36007368/140058660-62d5c55c-5a04-4831-ab1d-c0ddde33ea07.png)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Comment by Zanaxhir** [comment]
Is there another ticket or solution for this problem?
