### ISSUE TITLE
[Custom Components] Could not resolve single class custom component in angular library

### ISSUE THREAD

**Issue by Schwofel** [formio/angular#486]
Hello everyone,
i have a problem. I want to package my single class custom components into an angular library.
When i import the single class custom components js files and i try to build my library i get an error message.

Could not resolve './components/CustomLayout.js

My import looks like this:
import './components/CustomLayout.js';

Can you help me? What am i doing wrong here?

**Comment by merobal** [comment]
That example might be outdated, I only tested the Angular Components implementation

**Comment by Schwofel** [comment]
Hello,
if i import the js file in my application in the same workspace it works. But if i import the js file in a angular library and try to build i get an error that i could not be resolved.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
