### ISSUE TITLE
Builder Language Change

### ISSUE THREAD

**Issue by artel-ksikora** [formio/angular#493]
Good time of day.
Is the way to change change the language for formbuilder element, such as: "Label", "Label Position" ect.
![Annotation 2020-03-16 132632](https://user-images.githubusercontent.com/55102559/76753863-dc27d580-6789-11ea-826c-aa07c4ce7317.png)

**Comment by travist** [comment]
These are configured and changed the same way the renderer changes its language. You can see an example @ https://formio.github.io/formio.js/app/examples/language.html

**Comment by artel-ksikora** [comment]
Maybe I don’t understand something, but in the example, the setting is only for rendering, I searched the entire source code, but I didn’t find the text that is used in the editor itself (I’ll note again, not the one that we specify when creating form elements)

**Comment by travist** [comment]
The builder also should accept i18n configurations through the ```Formio.builder``` method like so.

```
Formio.builder(document.getElementById('builder'), formJSON, {
  i18n: {
    ...
  }
});
```

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
