### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by upexcel** [formio/angular#498]
**Custom Component With Lazy Loaded Modules**
Hi, I'm trying to implement custom component with lazy  loaded modules but I'm not able to work it out.
Please help me out.

I've Registered the custom component in app module then accessing it inside the lazy loaded modules. Here I can see the component in the basic section but while using it the preview is blank.

The [**Git Link**](https://github.com/upexcel/formio-question)
I've deployed it on [**Netlify**](https://inspiring-mclean-fa8f09.netlify.com/test)

In the demo above the first one is normally loaded and the other one is lazy loaded.
First one works but when we drag the rating in lazy loaded module it shows blank in preview.

**Comment by wag110894** [comment]
Hello @upexcel,
We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please contact support@form.io and we will provide you with our support package document.

**Comment by upexcel** [comment]
Thank you.
I'll look into that

**Comment by technokrat96** [comment]
same i found a problem

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
