### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by Schwofel** [formio/angular#503]
Hello everyone,
I want to use a custom formio component (single class like CheckMatrix.js) in an angular library.
If i import my js file how it is descripted in the wiki, i get an error that it could not be resolved.
If i understand correctly, that error happens because of the aot compiling and js files are ignored. 
So i tried to convert the js custom component file into a typescript file. 
Then i get an error that i can not set builderInfo because my exported class has only a getter for the  builderInfo property.

Also my custom component doesnt extend BaseComponent or NestedComponent. It extends Textfield. 

Thank you very much.

**Comment by wag110894** [comment]
Hello @Schwofel,

Thank you for reaching out!

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Let us know if you are interested by contacting support@form.io.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
