### ISSUE TITLE
[QUESTION] or maybe [BUG] calendar widget configuration not applying

### ISSUE THREAD

**Issue by HenriqueVilela** [formio/angular#522]
I notice that the widget configuration dont apply any change to the date picker, even the format has to be outside the widget configuration.

this is intencional?

![image](https://user-images.githubusercontent.com/38706785/79609061-74d4ac80-80cc-11ea-9808-3d9fc6c0a9bd.png)

**Comment by Deloriom** [comment]
@travist can you give some help in this? maybe you didn't understood what i wanted to ask in this issue, i can explain better if that is the case.

**Comment by travist** [comment]
I don't believe that the "time_24hr" flag will override the format. There is a format you can use to change it to 24 hour mode I believe. As far as I can tell this is expected.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
