### ISSUE TITLE
Load form from database and add into default form object

### ISSUE THREAD

**Issue by AleksandarKurta** [formio/angular#527]
Hello, i want to load form from db and set it to <form-builder [form]="form">. When i console.log in constructor or ngOnInit method data is there and it is set to form variable but the form  shows up only when i try to drag and drop not when the page is loaded. I tried to add [refresh]="refreshForm" after form is set but nothing changes, can someone help me?

**Comment by Peke-tupaea** [comment]
Experiencing the same issue, please help.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
