### ISSUE TITLE
[BUG] Error during compiling angular app, angular-formio v4.7.9

### ISSUE THREAD

**Issue by gladkiy** [formio/angular#534]
I have Angular v9.1.4 app and I updated angular-formio package up to v4.7.9 and see this error during compiling angular app:
```
ERROR in ./node_modules/angular-formio/__ivy_ngcc__/custom-component/custom-tags.service.js 27:7
Module parse failed: Unexpected token (27:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     ];
|     return CustomTagsService;
> }()    static ɵfac: ɵngcc0.ɵɵFactoryDef<CustomTagsService, never>;
|     static ɵprov: ɵngcc0.ɵɵInjectableDef<CustomTagsService>;
| );
```

**Comment by travist** [comment]
@merobal maybe you know what the cause is for this?

**Comment by merobal** [comment]
It seems it's related to Ivy. That file is a simple service.
Until Ivy is supported, try disable Ivy in angular.json
Related: #505

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
