### ISSUE TITLE
[Custom Components] Angular template HTML showing in "Default Value"

### ISSUE THREAD

**Issue by hbaldwinRPT** [formio/angular#540]
I've begun from the beginning again trying to get a select component to work, and noticed that with the standard example for the custom component when i just change the type to string and give it a standard input and not an angular rating tag the input shows up in the default value section but not in the preview, or in the builder, or renderer afterward. Confused as to why this happens and how to fix it.
![Annotation 2020-05-11 114138](https://user-images.githubusercontent.com/47833476/81599034-11613600-937d-11ea-855b-44570fd93d9d.png)

**Comment by kulandairaj** [comment]
@hbaldwinRPT  did you get any idea on this?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
