### ISSUE TITLE
[BUG]  Select Component - Multiple Values and set multiple default value

### ISSUE THREAD

**Issue by gismomtl** [formio/angular#609]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.7.5-rc.2
- Formio.js version: 4.9.19-rc.2
- Frontend framework: angular
- Browser: Chrome

## Steps to Reproduce
1. create a select component with
  - "Multiple Values" enabled
  - multiple value available (ex. A, B, C, D)
2. try to set "default value" to A & B
   "A","B" or A B ...

## Expected behavior
have the angular page displaying both default value

## Observed behavior
a string <"A","B"> is shown which is différent if we select A and B 
On Formio Admin page, the default selection appears correctly

**Comment by wag110894** [comment]
Hello @gismomtl 

We are aware of the issue with not being able to select multiple values using HTML5. The ticket for this issue is FJS-526. It is currently on our backlog. We welcome a pull request or have a process to expedite if you are interested.  

As for the issue where the strings combine as shown in the type de réponse,  can you try upgrading Angular formio to the latest and see if you are still experiencing this issue.

Have a great day.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
