### ISSUE TITLE
[Question] Select Component search when using paging

### ISSUE THREAD

**Issue by bandman0226** [formio/angular#627]
I am using a select component and using URL to an external source. I get the data just fine so I added limit and skip to the URL. This works fine as well but it seems to break searching inside the select component.

Is there an option to pass through to the external source the string that is being searched for?

**Comment by travist** [comment]
I believe this is the option called ```searchField``` property within the component JSON.  https://github.com/formio/formio.js/blob/master/src/components/select/editForm/Select.edit.data.js#L324

**Comment by bandman0226** [comment]
I see the field in the form but how do I get it in the url? 
I have skip={{skip}}&limit={{limit}}  in the URL but if I add searchField={{searchField}} to that then it does not work.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
