### ISSUE TITLE
[Question] Where cai i found compatibility between angular-formio with angular ?

### ISSUE THREAD

**Issue by fzucaro** [formio/angular#630]

**Comment by travist** [comment]
Are you referring to Angular versions that we support?  Currently the place to find that is in the package.json file where it shows the version that is supported. We are currently working toward coming out with an Angular 10 release which should be ready for testing within the next couple of weeks.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
