### ISSUE TITLE
How do I disable some settings in the form element editor modal?

### ISSUE THREAD

**Issue by mhamadhdeib** [formio/angular#631]
![image](https://user-images.githubusercontent.com/48261240/95061719-a1c15e00-0704-11eb-9141-dc3db1bdc9aa.png)

For example if I want to disable the description or placeholder option.

Thanks in advance

**Comment by wag110894** [comment]
Hello @mhamadhdeib, Have you taken a look at this documentation: https://formio.github.io/angular-demo/#/forms/custom-builder?

**Comment by Kadhiresan-K** [comment]
@mhamadhdeib You can disable the placeholder option like below

"editForm": {
    "textfield": [
        {
            "key": "display", //Tab name
            "ignore": false,
            "components": [
                {
                    "key": "placeholder", //Property name
                    "ignore": true
                }
            ]
        }
    ]
}

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
