### ISSUE TITLE
[BUG] File field is not generating the base64 content in the submission object when uploading large files

### ISSUE THREAD

**Issue by jesusduranevenbytes** [formio/angular#640]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.8.0-beta.7
- Frontend framework: Angular v9.1.11
- Browser: Google Chrome
- Browser version: Version 86.0.4240.111 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a form with a file field with the following settings:
 ```
{
    "label": "Video",
    "tableView": false,
    "storage": "base64",
    "dir": "/",
    "uploadOnly": true,
    "webcam": false,
    "fileTypes": [
        {
            "label": "MP4",
            "value": ".mp4"
        },
        {
            "label": "MOV",
            "value": ".mov"
        },
        {
            "label": "AVI",
            "value": ".avi"
        },
        {
            "label": "MKV",
            "value": ".mkv"
        }
    ],
    "fileMaxSize": "2GB",
    "multiple": true,
    "validate": {
        "multiple": true
    },
    "key": "video",
    "properties": {
        "Data.System.Files.Type": "Video"
    },
    "type": "file",
    "input": true
}
```
2. Upload a large file (video), around 450MB.
3. Submit the form

## Expected behavior
In the submission JSON, the file object should have the content of the file in base64 encoding in the url property
## Observed behavior
The url property of the file object is an empty string

**Comment by wag110894** [comment]
@jesusduranevenbytes,

We recommend that you do not use base64 as your file storage if you are needing to upload large files.
We recommend using S3, using a custom URL, Dropbox, or Azure Blob Storage. Here is our documentation on these other file storage: https://help.form.io/integrations/filestorage/

I hope that this helps.

**Comment by jesusduranevenbytes** [comment]
@wag110894,

Thank you for your answer.

We are using Cloud Storage for Firebase as our server for storing files, and specifically Firebase Storage for Web library to manage the file uploads and downloads. We would need the file as [base64, File object, byte array or string (base64, base64url or data_url)](https://firebase.google.com/docs/storage/web/upload-files) in order to be able to upload the files directly from the client side.

Is there any possible workaround so we can upload large files and keep using Firebase Storage for Web?

**Comment by travist** [comment]
This would need to be a custom file upload provider as seen @ https://github.com/formio/formio.js/tree/master/src/providers/storage.  It may not be that complicated since you have other examples there, and then you can set the provider value in the JSON of the component and it will upload to that provider.

**Comment by jesusduranevenbytes** [comment]
Thank you for your responses, we will look into it.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
