### ISSUE TITLE
Angular custom component in Nested component is not working properly

### ISSUE THREAD

**Issue by gouravsachdeva** [formio/angular#666]
Hello,

1.) We are adding angular custom components inside a Panel component and assigning the whole as a Nested component. It's working only when the panel component is expanded and once we'll collapse and expand again. custom component's element is not getting rendered. 

**Before Collapse**

![image](https://user-images.githubusercontent.com/24933333/100318229-b70b8800-2fe3-11eb-9f9f-b70193866119.png)

**After Collapse and Expand**

![image](https://user-images.githubusercontent.com/24933333/100318437-09e53f80-2fe4-11eb-9c33-3f14e0b764de.png)

2.) In the case of dataGrid component inside a nested component, angular custom components are not visible.

![image](https://user-images.githubusercontent.com/24933333/100318867-c4754200-2fe4-11eb-95c6-23ff2a20fb0b.png)

I would be really grateful for your help.

Thanks a lot and best regards,
Gourav Sachdeva

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
