### ISSUE TITLE
[Question] Showing Chart in Angular 2+ (preferably Angular 9)

### ISSUE THREAD

**Issue by SAkhil95** [formio/angular#684]
Hi Team,

I am trying to add/use charts in our form.

I noticed that there's already a solution to achieve this but the implementation uses Angular 1.x.
Reference :: https://github.com/formio/formio/issues/198

I just wanted to request if any such implementation can be provided for Angular 2+ (preferably Angular 9)

**Use case ::** 
I need to implement a Risko meter which will get calculated based on some responses and gets changed accordingly just like the below image.

![image](https://user-images.githubusercontent.com/39143963/101773195-7434ce80-3b12-11eb-9dc4-a3a0d42c16ab.png)

Thanks

**Comment by travist** [comment]
That would be a cool component. Unfortunately I cannot think of anyone implementing a component that does such a thing, so you will need to implement this one on your own.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
