### ISSUE TITLE
[Custom Components] with Calculated value

### ISSUE THREAD

**Issue by mayankhpr** [formio/angular#686]
Hi Team,
Calculated value is not working with custom component.  I have created RadioButtonsComponent. RadioButtonsComponent implements "FormioCustomComponent". I need "calculateValue" filed information in my TS file.

**Comment by wag110894** [comment]
Hello @mayankhpr,

Thanks for reaching out! 

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.

Please let me know if you would like to view our pricing document.

Thank you,

William Gay

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
