### ISSUE TITLE
Translation of custom components is not documented for angular-formio

### ISSUE THREAD

**Issue by fhasni** [formio/angular#690]
How to make custom components translatable in angular-formio? translation of angular custom components is not documented.

**Comment by wag110894** [comment]
Hello @fhasni,

Thanks for reaching out!

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period. We will assign one of our senior developers to work directly with you in online sessions.

Please let me know if you would like to view our pricing document.

Thank you,

William Gay

**Comment by fhasni** [comment]
How can I reach you to get this support package?

**Comment by wag110894** [comment]
Hello @fhasni, 

You can contact support@form.io and say that you are interested in a support package.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
