### ISSUE TITLE
Default value for custom class

### ISSUE THREAD

**Issue by abhishek0196** [formio/angular#720]
Hello form io community I am looking for a solution which helps me to set the default value for the custom class.
I wanted to hard code the value for this custom class for each type of controls, so that I can hide it from the user, while they are  building the form.
Thanks.

**Comment by wag110894** [comment]
Hello @abhishek0196 

Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you and have a great day!

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
