### ISSUE TITLE
[Question] refresh data source url in Select Component

### ISSUE THREAD

**Issue by ghost** [formio/angular#729]
Hi,
Is there a way to refresh data source in Select Component when "Data Source Type" = URL?

The *select component* shows a list of users that are getting from **another app**.
Then at **another app**, admin adds some users.

So how can the select component show the newly added users without reloading the page?

Actually, I have to reload the page to see the new values. However

Thanks for your help!

**Comment by travist** [comment]
There should be a property called "Refresh Options On" that allows you to refresh the options when another field changes. This is used to perform conditional selects (where the results of one select dropdown are dependent on the value selected of another dropdown).

**Comment by thanhvietnguyen255** [comment]
Thanks for your answer.

As I mentioned above. I have 2 applications (A - use formio) and (B).
The **select** calls API of application (B) to get a list of users.

At the application (A), I open the **select**, it shows 10 users.
Then at the application (B), I add 2 more users. Therefore, at the application (A) when I open the **select** again then it should show 12 users instead of 10 users.

**Notes**: it shows 12 users after I reload the page. 
**My expectation is no need to reload**

It doesn't involve other field changes, so I can't use "Refresh Options On"

**Comment by thanhvietnguyen255** [comment]
Could you please give me any solutions to solve the issue?
