### ISSUE TITLE
How to implement attributes input from HTML component in my custom component?

### ISSUE THREAD

**Issue by TimurAztec** [formio/angular#743]
How to implement attributes input from HTML component in my custom component?
I want to make so when people enter attributes into edit form they would apply on input
And how to apply CSS classes on input via edit form?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
