### ISSUE TITLE
[Custom Components] How to create custom component with data source api url

### ISSUE THREAD

**Issue by kulandairaj** [formio/angular#746]

**Comment by edwinanciani** [comment]
What do you mean by data source api?

**Comment by kulandairaj** [comment]
I want to get data from api for my custom checklist box component

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
