### ISSUE TITLE
X button issue in nested form

### ISSUE THREAD

**Issue by nagashreebg** [formio/angular#761]
We have a nested form. This nested form has a select component.

There are couple of issues with this.

1. The x button on the inner form does not work when we click on it. However, if we click a little bit outside of the active window, a showModalDialog is shown asking if we want to clear the changes. This is the first issue. 

2. The second issue is that when the 'Yes, Delete it' option is chosen, the values in the inner form are not cleared. They persist. For e.g. if we have a select component and we select one of the values, that value remains even when we reinvoke the inner form. This is inconsistent with the option asking if we want to clear the values.

We are using Form.io version 4.12.0.

Could you please let me know how to overcome these problems or if we are doing anything wrong. Any help would be appreciated.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
