### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by buseodaci** [formio/angular#766]
Hi,
I created a custom component and using this component i can save the data. But when i want to see data with form its not working. 
You can see this is my form.
![image](https://user-images.githubusercontent.com/25960852/116855211-afd74e80-ac01-11eb-806d-883129188d67.png)
 Normally i have data like this` {rate:10}` . For giving this data to form im using submission which like this `{data: { rate:10 } }`.
For other Formio components submission work fine. 
![image](https://user-images.githubusercontent.com/25960852/116855473-19575d00-ac02-11eb-9ee3-9f3dc9d0c433.png)
But custom components rate data turning NaN.
![image](https://user-images.githubusercontent.com/25960852/116855645-663b3380-ac02-11eb-944b-f675a9d1228c.png)

@merobal Is there any way can i fix this? What im missing ?

Thank you

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
