### ISSUE TITLE
Custom Form Builder[Question] 

### ISSUE THREAD

**Issue by sujithakamineni** [formio/angular#768]
Hi,

When using custom form builder and passing custom fields to be displayed in basic components through properties in **options** in the below example. Can we pass json schema to form builder for loading custom fields on the left side. Please suggest any better approaches. 

<img width="1010" alt="Screen Shot 2021-05-03 at 5 36 52 PM" src="https://user-images.githubusercontent.com/69477326/116949218-710fbb80-ac36-11eb-9814-3aefbde51f7c.png">

public options = {
    builder: {
      basic: false,
      advanced: false,
      data: false,
      custom: {
        title: 'User Fields',
        weight: 10,
        **components: {},**
      }
}
<div class="pt-5">
    <form-builder [form]="form" [options]="options" (change)="onChange($event)"></form-builder>
</div>

Thank you,
Sujitha

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
