### ISSUE TITLE
[Question] - multi-language form FormioOptions

### ISSUE THREAD

**Issue by sharmav007** [formio/angular#769]
For a multi-language form how we can store FormioOptions related to form. The create form api only accept form object, how and where options related to the form can be saved and retrieved.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
