### ISSUE TITLE
deleteComponent event not firing when remove components inside a panel

### ISSUE THREAD

**Issue by jyoti0291** [formio/angular#770]
Hi Team,

<img width="799" alt="Screenshot 2021-05-05 at 8 12 44 PM" src="https://user-images.githubusercontent.com/22149791/117159873-46606700-adde-11eb-98ce-00f5fafc58ad.png">

My form has a panel which contains multiple components. I detect the changes in form through above onChange method which triggers on every update and delete of components except when I remove a component which lies inside the panel as shown in the below image.

<img width="1088" alt="Screenshot 2021-05-05 at 8 00 57 PM" src="https://user-images.githubusercontent.com/22149791/117157955-a5bd7780-addc-11eb-9d45-cf4d9d5467b3.png">

Because of this issue I am not able to update my form components. Anyone has any idea about it?

Formio Version: 5.0.0
Angular Version: 9

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
