### ISSUE TITLE
select component edit window default value  not hide

### ISSUE THREAD

**Issue by rengarajan098015** [formio/angular#776]
Hi,

let me know how to remove select component edit window **default value, custom default value, calculated value.**

![image](https://user-images.githubusercontent.com/77962234/118488609-88bc6900-b739-11eb-8de0-795cf5a20b42.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
