### ISSUE TITLE
Select component additional column for user input

### ISSUE THREAD

**Issue by rengarajan098015** [formio/angular#777]
HI,

Normal Select control edit form window
![image](https://user-images.githubusercontent.com/77962234/118490249-5ca1e780-b73b-11eb-9aa3-3e73960b5557.png)

want to to get additional column for user input,  3 column select dropdown  or check box true/false values.
our expected outputs looks like

![image](https://user-images.githubusercontent.com/77962234/118491099-447e9800-b73c-11eb-9ecb-fa31bcd65149.png)

let me know how to achieve this?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
