### ISSUE TITLE
[Question] Possibilities for customizing headers and/or cookies

### ISSUE THREAD

**Issue by ddurham2** [formio/angular#780]
I'm in a situation, using the opensource edition, where there is a reverse proxy between the frontend and formio backend.  And this reverse proxy has some additional authorization to do.

When using, e.g., a `<formio>` element, I need some way for it to either:
1. send the 'Authorization' header with my supplied value
2. or some other custom header with said value
3. or have cookies sent by having the [withCredentials=true](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) be passed to the XHR call.

(Preferably option 3)

I've dug into the code enough to know that this is probably a function of formiojs, if it's at all possible.  i.e. it doesn't appear to be using Angular's HttpClient, so an HttpInterceptor will have no effect.

If the suggestion is to manipulate the formio.js object, then please describe how to do that (e.g. by injecting my own FormioService or FormioPromiseService and what to do in it)?  I think I'm seeing it create a new Formio(js) instance for each `<formio>` element.  Thus, each instance would have to be manipulated.  And I'm not even sure how to actually get at the instance of Formio(js) that a particular `<formio>` element would possess. 

Thanks in advance!

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
