### ISSUE TITLE
[Question]  How to Enable Formio-grid Column Filtering & Sorting

### ISSUE THREAD

**Issue by potandpornstarsdev** [formio/angular#781]
Hi Everyone,

We are trying to use the formio-grid with the enableFiltering: true option set in the component but it has not effect. 

Looking at the @angular/formio grid package I do not see the gridOptions property on the interface. 

What is the proper way to enable filtering across all the columns? Here is the element configuration we are using. with Angular 11. 

<formio-grid
src="{{ config.appUrl }}/dataupdate/"
createText="New Update"
(rowSelect)="onSelect($event)"
(createItem)="onCreateItem()"
gridOptions="{'enableFiltering': true}"
></formio-grid>

**Comment by brandlighting** [comment]
we are trying to get column filtering and sorting enabled as well to no avail. Has anyone been able to pass the gridOptions to the ui-grid within the component class? The formio-grid docs are for angularjs and it appears to be a different implementation as the @formio/angular library. Any help would be great!

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
