### ISSUE TITLE
Need to have custom error comments while creating form[Question] 

### ISSUE THREAD

**Issue by Chayannath19** [formio/angular#806]
Need to give custom comments like this, how it is coming up " API Key is not unique" While creating the form, is there any way to do it?

![image](https://user-images.githubusercontent.com/89972934/131820785-b7be3501-914d-45d3-b787-37488674261c.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
