### ISSUE TITLE
[Question] Preventing Component Editor from being closed when clicking on modal background

### ISSUE THREAD

**Issue by dalesingh47** [formio/angular#811]
This question is in reference to the form editor.

Currently, when a component editor is open, it can be closed by clicking on the "X" in the top right hand corner, or by clicking on the modal background.

Is it possible to prevent the the editor from being closed when the modal background is clicked? This seems to be a big deal for some users.

If not, is it possible to add a feature request for this?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
