### ISSUE TITLE
Angular v5 Stabile Version

### ISSUE THREAD

**Issue by 4bs0l3m** [formio/angular#827]
### Discussed in https://github.com/formio/angular/discussions/826

<div type='discussions-op-text'>

<sup>Originally posted by **enesozer** October 19, 2021</sup>
Hello, I working to Angular v5 at now and I want to use this project. Which i can use version of the project?

My package.json

> "@angular/animations": "^5.2.10",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",</div>

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
