### ISSUE TITLE
How to add a new field in textfield data tab formio Angular? 

### ISSUE THREAD

**Issue by jyotiyi** [formio/angular#829]
After drag textfield component this is how it appears, is it possible to add extra field in data tab? And assign a calculated value to textfield.
![image](https://user-images.githubusercontent.com/92496788/139003996-9fc85db2-3c7e-42d5-8e46-d3d12b4a2829.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
