### ISSUE TITLE
[BUG]  multipleOf 0.1 validation is throwing "not a multiple of 0.1" error on certain values (0.3, 0.6, 0.7) & more

### ISSUE THREAD

**Issue by NeilWoodComputing** [formio/angular#830]
## Environment
Please provide as many details as you can:

number field throwing incorrect errors:
multipleOf 0.1 validation is throwing "not a multiple of 0.1" error on certain values (0.3, 0.6, 0.7) & more

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:  7.15.1 
- Frontend framework: Angular
- Browser: Chrome -  84.0.4147.105
- Browser version: -  84.0.4147.105

## Steps to Reproduce
1. create a number field using the validation of multipleOf = 0.1 
2.  insert value 0.3  into the field 
3.  observe error "not a multiple of 0.1"

## Expected behavior
I should only see multipleOf errors when the entered number violates the validation

## Observed behavior
I see the error thrown on multiple valid multiples of 0.1
![Capture](https://user-images.githubusercontent.com/30634968/140501268-03d1aa98-c14f-4b70-8829-a06e34ea9098.PNG)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
