### ISSUE TITLE
[Question] [Custom Components] Value prop as an array

### ISSUE THREAD

**Issue by smirnov-d** [formio/angular#831]
Hi, there. I try to use a custom component with array of strings, but @input value changed to the string (first element of the array) after form submission. Could you please provide an example how to use a custom component with an array.
```
this.updateValue(['1','2','3']) ; 
// 'value' is [  "1", "2", "3" ];
submit form
// 'value' is  "1";
```

Also, when I try to provide the <formio ... [submission]="{ fieldName: ['string1', 'string2'] } " > the value prop in the component is equal to 'string1'

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
