### ISSUE TITLE
When we click on already uploaded file, it opens new  tab on browser

### ISSUE THREAD

**Issue by Rahuly2k** [formio/angular#834]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```
![fio-update 2](https://user-images.githubusercontent.com/8709017/141960254-7597b032-d4d8-45a0-8931-53008e759a79.png)

![fio-update-1](https://user-images.githubusercontent.com/8709017/141960340-ca008677-0640-44ab-8a71-36053c5785fb.png)

**Comment by Rahuly2k** [comment]
I am using angular framework, where I created one template and upload file. But when user logged in to their profile all data pre filled properly with file. but when click on already uploaded file (from user profile) it open new tab with file name.

**Comment by wag110894** [comment]
Can you provide a form embed as well as a video?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
