### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by shahzadiiui2015** [formio/angular#843]
how i can pass value to default value of textarea using as quill editor.  i am using custom component which have hyper links added into textarea editForm. is there any way to do that how i can achieve this. i have attached the image for more detail.
![customTextArea](https://user-images.githubusercontent.com/38350534/144721389-b417b601-22c7-470b-8023-5b772a740984.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
