### ISSUE TITLE
[Question] How to listen on keyup, keydown and keypress events

### ISSUE THREAD

**Issue by phinguyen202** [formio/angular#844]
Hi everyone,

Many thanks for awesome library.

I'm trying to listen keyboard event on an textfield. I have try to use "Advanced Logic" with "Event" type and input the "keyup" event then adding an simple action. However it doesn't work. If I change the event to "focus" then it works well.

Do I miss something to make it works?

The versions I'm using are:
`
@formio/angular": "^5.2.0",
"formiojs": "^4.14.0"
`

Best,
Phi

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
