### ISSUE TITLE
File Component is not working

### ISSUE THREAD

**Issue by khadimullah1** [formio/angular#845]
Formio File component is not working in angular
![image](https://user-images.githubusercontent.com/77723322/146926972-bc423339-98b7-49bf-821b-9574d4989a6f.png)
 
it give below error
![image](https://user-images.githubusercontent.com/77723322/146927468-651df9d0-4a77-4115-9167-657452d22b2a.png)

schema is given as below
![image](https://user-images.githubusercontent.com/77723322/146927617-d36dc697-d525-4934-b57c-bc7383b03dba.png)

any type of help will be appreciated, 
Thanks in advance

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
