### ISSUE TITLE
Installation Failed [BUG] 

### ISSUE THREAD

**Issue by abdulhamid93** [formio/angular#847]
Installation failed.
Please help me.

![image](https://user-images.githubusercontent.com/80948405/147552020-65a033d1-9d81-4509-bcdb-5e30e2146bca.png)

**Comment by fedesnieg** [comment]
Any workarounds?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
