### ISSUE TITLE
[Question] I have embedded form-builder in my angular project. Do I have to purchase it or something to utilize all its functionality or what? Please refer to the attached screensot.

### ISSUE THREAD

**Issue by AliZain036** [formio/angular#863]
![image](https://user-images.githubusercontent.com/45128768/156512686-50df210d-eb45-4544-8bf5-b7b13e0a3173.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
