### ISSUE TITLE
Set form as invalid from the custom component

### ISSUE THREAD

**Issue by reshiin** [formio/angular#865]
Hi! I just want to ask if its possible to set the form as invalid from the custom component itself.
I have created a validation inside my custom component, if that validation fails I want to disable the submit button and tag the form as invalid programmatically inside the custom component.

Hoping for your kind assistance on this. Thanks!

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
