### ISSUE TITLE
How to hide/disable searchbar in sidebar formbuilder?

### ISSUE THREAD

**Issue by chintuyadavsara** [formio/angular#866]

**Comment by chintuyadavsara** [comment]
@travist Please help

**Comment by Amir-MP** [comment]
u can use css , in styles.css use this code

.builder-sidebar_search {
  display: none;
}

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
