### ISSUE TITLE
How to remove delete option for default submit button in angular formio? 

### ISSUE THREAD

**Issue by chintuyadavsara** [formio/angular#867]

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
