### ISSUE TITLE
Using search bar for components stops the ability to select different tabs on the builder palette

### ISSUE THREAD

**Issue by chintuyadavsara** [formio/angular#868]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: Angular 10
- Formio.js version: 4.11.5
- Frontend framework: Angular with Bootstrap
- Browser: Google Chrome
- Browser version: 99.

## Observed Issue
1. Using search bar for components stops the ability to select different tabs on the builder palette
2. Unable to select other tabs

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
Search
![image](https://user-images.githubusercontent.com/26032330/158538199-ef090c5c-1b15-4e10-a67d-b2a83369c3de.png)
Tab not opening
![image](https://user-images.githubusercontent.com/26032330/158538247-3ecce999-1d30-4a22-bd35-ec5e893e09e6.png)

**Comment by chintuyadavsara** [comment]
Same kind of issue observed in `formiojs` as well
https://github.com/formio/formio.js/issues/3893

**Comment by wag110894** [comment]
Hello @chintuyadavsara, 

We are not able to replicate this issue using Formio.js 4.14.1. Can you try upgrading and see if the issue still exists? 

Thank you.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
