### ISSUE TITLE
Custom Component extending Well Component - not showing Drop Zone

### ISSUE THREAD

**Issue by jprashant28** [formio/angular#869]
I am trying to create a custom nested component - so that I can change the way the children component are rendered.  So I started off by extending a Well Component since it has the simplest Edit Form.  While I am able to drag my custom component onto the Form, I am unable to get a drop zone for it - and thus am unable to add children components to it (like buttons etc.).

What am I missing?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
