### ISSUE TITLE
[BUG] Options support in @formio/angular

### ISSUE THREAD

**Issue by otebos** [formio/angular#881]
## Environment
This issue regards the formBuilder in @formio/angular 5.2.2 and is not observed in angular-formio 4.11.5
When I pass options in angular-formio version, it works.
When I pass options in @formio/angular version, typescript screams about FormioOptions properties.
When I changed FormBuilderComponent.options from
`options?: FormioOptions;`
to
`options?: any;`
There is no error but still nothing happens.

Looking at FormioOptions definition TypeScript is correct as there are no properties that are defined in documentation and samples like `editForm`, `builder`, `buttonSettings` etc ...

How should I pass options to form builder? 
Or @formio/angular is not for use and I should use angular-formio version?

- Hosting type
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.14.7
- Frontend framework: Angular 13
- Browser: n/a
- Browser version: n/a

## Steps to Reproduce
1. define options like ```formioOptions = {editForm: { textfield: [{ key: 'api', ignore: true }] }}```
2. pass to ```<form-builder [form]="form" [options]="formioOptions"></form-builder>```

## Expected behavior
Options are applied

## Observed behavior
TypeScript error
`error TS2559: Type '{ editForm: { textfield: { key: string; ignore: boolean; }[]; }; }' has no properties in common with type 'FormioOptions'. `

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
