### ISSUE TITLE
Error loading the Data Table wiki page

### ISSUE THREAD

**Issue by Mimisss** [formio/angular#899]
When trying to navigate to https://github.com/formio/angular-formio/wiki/Data-Table I get the following message:

`You do not have permission to update this wiki.`

The long story is, I have been following your Application Development instructions (Angular): https://help.form.io/intro/application and I am trying to find documentation on how to translate the data table elements (pager etc) and add searching.

Is such documentation available?

**Comment by Mimisss** [comment]
Maybe the following page should be the target of the broken link?

https://github.com/formio/angular/wiki/Submission-Table

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
