### ISSUE TITLE
[Question] looping through submission data in HTML Element

### ISSUE THREAD

**Issue by pmatulionis** [formio/angular#907]
Is it possible to loop through the submission data in formio HTML Element? I have a wizard type form and 6 pages in it with various form components. At the last page I am trying to do a preview page of the entire form, but just in HTML. So in that last page I added an HTML Element component, for e.g.:

```
<div>
   <div>Name: {{data.name}}</div>
   <div>Surname: {{data.surname}}</div>
</div>
```

These works fine and replaces template elements with the actual values from submission data.
However I also have a DataGrid component where I enter multiple rows and I would like to display the values as table.
I can't figure out what templating language is being used here. By some failures I see that lodash is failing, but trying to find an example with for loop via data grid elements I end up with nothing.

Is it event possible and if so could you point me to the right direction please?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
