### ISSUE TITLE
[BUG] DataGrid component shoots up CPU consumption and page slows down after 30 rows

### ISSUE THREAD

**Issue by mcsarathkumar** [formio/angular#909]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 5.2.0
- Formio.js version: 4.13.9
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 105.0.5195.125

## Steps to Reproduce
1. Create DataGrid Component with 10 columns (Mix of Text fields, date, Checkbox, numberfield)
2. Create 30 rows and above and fill data

## Expected behavior
- Datagrid component should work without issues or lag in page

## Observed behavior
- In text fields, spaces are deleted directly after typing them
- In number fields, the comma often is ignored (it's used as the decimal delimiter)
- When switching the fields with the tabulator, the cursor often just disappears and doesn't jump to the next field
- In general, the form is lagging and slow

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
