### ISSUE TITLE
Is it possible to change the theme on a panel live?

### ISSUE THREAD

**Issue by Chris-Grell** [formio/angular#911]
I have a custom panel component and was wondering if it were possible to set the theme in the schema() to a method that would return specific themes.

Thanks

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
