### ISSUE TITLE
[Question] Unable to use custom date format(dd-MM-yyyy) for component date

### ISSUE THREAD

**Issue by mohammadaaqib** [formio/angular#912]
I am using angular formio 4.11.5 with this version everything looks good except the date picker with the custom date (dd-MM-yyyy), but it is working fine with the default format (yyyy-MM-dd)
 
 this issue is seemed fix with formiojs https://github.com/formio/formio.js/issues/4094 but I think  angular formio is not updated.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
