### ISSUE TITLE
[Question] Compatibility matrix and build from source

### ISSUE THREAD

**Issue by mubinahmed** [formio/angular#928]
I want to know if there is any compatibility matrix for different versions of formiojs, formio-angular, and angular?
I would also like to know if there is any documentation on how to build this from source.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
